### ISSUE TITLE
Improve "how to build testsuites tutorial" and align "testsuites-management description"

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-tutorial#11]
Hi Holger,
please take over the branch from https://github.com/test-fullautomation/robotframework-tutorial/pull/9.
You can create a new branch based on this. I wanted to merge, but there is currently a merge conflict.

Please realize your proposal how to improve the tutorial and documentation. Please reuse as much as possible from Sons texts and scripts.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Hi Thomas,
please decline:
https://github.com/test-fullautomation/robotframework-tutorial/pull/9
https://github.com/test-fullautomation/robotframework-tutorial/pull/10
From current develop I created a new branch named HolQue/feat/testsuites_tutorial_further_development
and I put in there all changes from these pull requests step by step:
https://github.com/test-fullautomation/robotframework-tutorial/pull/12

**Comment by test-fullautomation** [comment]
Implemented with #12
